---
driver:
  name: ec2
  associate_public_ip: true
provisioner:
  name: chef_zero
  chef_license: accept
  log_level: <%= ENV['LOG_LEVEL'] || 'info' %>
transport:
  connection_timeout: 10
  connection_retries: 5
platforms:
  - name: windows-2019
    driver:
      require_chef_omnibus: '17.9.26'
suites:
  - name: default
    run_list:
      - recipe[winsw::_winsw_integration_fixture]