---
driver:
  name: vagrant
provisioner:
  name: chef_zero
platforms:
  - name: win2012r2
    driver:
      box: eval-win2012r2-standard-chef15
      vm_hostname: win2012r2
      boot_timeout: 18000
      product_name: chef
      require_chef_omnibus: 15.3.14
      vagrantfiles:
        - Vagrantfile.rb
      customize:
        nictype1: 82540EM
      provision: true
suites:
  - name: default
    run_list:
      - recipe[winsw::_winsw_integration_fixture]
