name             'winsw'
maintainer       'github1'
maintainer_email 'github1@github.com'
license          'MIT'
description      'Installs/Configures winsw'
long_description 'Installs/Configures winsw'
version          '2.0.0'
source_url       'https://github.com/github1/winsw-cookbook'
issues_url       'https://github.com/github1/winsw-cookbook/issues'
chef_version     '>= 12.6.0'
supports         'windows'