name             'winsw'
maintainer       'github1'
maintainer_email 'github1@github.com'
license          'MIT'
description      'Installs/Configures winsw'
long_description 'Installs/Configures winsw'
version          '3.1.4'
source_url       'https://github.com/github1/winsw-cookbook'
issues_url       'https://github.com/github1/winsw-cookbook/issues'
chef_version     '>= 14.0.0'
supports         'windows'